import { readFile, readdir, mkdir, writeFile, access, unlink } from 'node:fs/promises';
import { resolve, dirname, relative, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { parseArgs } from 'node:util';
import { build as bundle } from 'esbuild';

const root = fileURLToPath(new URL('../', import.meta.url));
const { values } = parseArgs({ options: { target: { type: 'string' } }, strict: true });
if (!values.target)
  throw new Error('Usage: node scripts/export-haru.mjs --target <하루단어 checkout>');
const target = resolve(values.target);
const hosting = JSON.parse(await readFile(join(target, '.openai/hosting.json'), 'utf8'));
if (hosting.project_id !== 'appgprj_6ab0a3cbaaa08191a05b0bcdf62df225')
  throw new Error('하루단어 사이트 식별자가 다릅니다.');
const output = join(target, 'public/card-studio');
const sha = (bytes) => createHash('sha256').update(bytes).digest('hex');
async function files(folder) {
  const entries = await readdir(folder, { withFileTypes: true });
  const result = [];
  for (const entry of entries) {
    if (entry.isSymbolicLink()) throw new Error('Symbolic links are not exportable');
    const path = join(folder, entry.name);
    result.push(...(entry.isDirectory() ? await files(path) : [path]));
  }
  return result.sort();
}
let previousFiles = [];
try {
  await access(output);
  const previous = JSON.parse(await readFile(join(output, 'source.json'), 'utf8'));
  if (previous.format !== 'en-card-studio-v1') throw new Error('관리되지 않은 출력 폴더입니다.');
  previousFiles = Object.keys(previous.files);
  for (const [path, hash] of Object.entries(previous.files)) {
    const full = resolve(output, path);
    if (!full.startsWith(output + '/') && !full.startsWith(output + '\\'))
      throw new Error('Invalid export path');
    if (sha(await readFile(full)) !== hash)
      throw new Error(`수동 변경이 있어 덮어쓸 수 없습니다: ${path}`);
  }
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
  // An existing directory without the provenance file must not be overwritten.
  try {
    await access(output);
    throw new Error('기존 폴더에 source.json이 없습니다.');
  } catch (missing) {
    if (missing.code !== 'ENOENT') throw missing;
  }
}
const serverDir = join(target, 'lib/server');
const serverFiles = ['card-automation.generated.mjs', 'card-automation.generated.d.mts'];
const serverManifest = join(serverDir, 'card-automation.generated.json');
try {
  const previous = JSON.parse(await readFile(serverManifest, 'utf8'));
  if (
    previous.format !== 'en-card-ai-relay-v1' ||
    Object.keys(previous.files).sort().join(',') !== [...serverFiles].sort().join(',')
  )
    throw new Error('관리되지 않은 AI 서버 명세입니다.');
  for (const name of serverFiles)
    if (sha(await readFile(join(serverDir, name))) !== previous.files[name])
      throw new Error(`수동 변경이 있어 덮어쓸 수 없습니다: ${name}`);
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
  for (const name of serverFiles) {
    try {
      await access(join(serverDir, name));
    } catch (missing) {
      if (missing.code === 'ENOENT') continue;
      throw missing;
    }
    throw new Error('기존 AI 서버 파일에 명세가 없습니다.');
  }
}
const build = spawnSync(
  process.execPath,
  [
    join(root, 'node_modules/vite/bin/vite.js'),
    'build',
    '--base',
    '/card-studio/',
    '--outDir',
    'dist-haru',
  ],
  {
    cwd: root,
    env: { ...process.env, VITE_HARU_STUDIO: 'true' },
    stdio: 'inherit',
  },
);
if (build.status !== 0) process.exit(build.status ?? 1);
const server = await bundle({
  absWorkingDir: root,
  entryPoints: ['src/automation/relay-server.ts'],
  bundle: true,
  platform: 'browser',
  format: 'esm',
  target: 'es2022',
  minify: true,
  write: false,
  metafile: true,
  banner: { js: '// Generated by EN_Card/scripts/export-haru.mjs. Do not edit.' },
});
const declarations = `// Generated by EN_Card/scripts/export-haru.mjs. Do not edit.
export type RelaySiteConfig = {
  DB?: D1Database;
  card_studio_enabled?: string; card_studio_owner_id?: string; card_studio_bridge_secret?: string;
  google_ai_enabled?: string; groq_ai_enabled?: string; google_api?: string; groq_api?: string;
};
export declare function handleCardAutomationRelay(request: Request, config: RelaySiteConfig,
  transport?: typeof fetch, clock?: () => number): Promise<Response>;
`;
const serverSource = createHash('sha256');
for (const path of [
  ...Object.keys(server.metafile.inputs).filter((p) => !p.includes('node_modules')),
  'package-lock.json',
].sort()) {
  serverSource.update(path);
  serverSource.update(await readFile(join(root, path)));
}
const serverBytes = [server.outputFiles[0].contents, Buffer.from(declarations)];
await mkdir(serverDir, { recursive: true });
for (let i = 0; i < serverFiles.length; i++)
  await writeFile(join(serverDir, serverFiles[i]), serverBytes[i]);
await writeFile(
  serverManifest,
  JSON.stringify(
    {
      format: 'en-card-ai-relay-v1',
      sourceSha256: serverSource.digest('hex'),
      files: Object.fromEntries(serverFiles.map((name, i) => [name, sha(serverBytes[i])])),
    },
    null,
    2,
  ) + '\n',
);
const sourceFiles = [
  join(root, 'index.html'),
  ...(await files(join(root, 'src/web'))),
  ...(await files(join(root, 'src/shared'))),
];
const source = createHash('sha256');
for (const path of sourceFiles) {
  source.update(relative(root, path).replaceAll('\\', '/'));
  source.update(await readFile(path));
}
const hashes = {};
for (const path of await files(join(root, 'dist-haru'))) {
  const name = relative(join(root, 'dist-haru'), path).replaceAll('\\', '/');
  if (name === '_headers') continue;
  const destination = join(output, name);
  await mkdir(dirname(destination), { recursive: true });
  const raw = await readFile(path);
  const bytes = /\.(html|css|js|txt)$/.test(name)
    ? Buffer.from(raw.toString('utf8').replace(/\r+\n/g, '\n').replace(/\r/g, '\n'))
    : raw;
  await writeFile(destination, bytes);
  hashes[name] = sha(bytes);
}
for (const name of previousFiles) {
  if (!(name in hashes)) await unlink(resolve(output, name));
}
// The host Site owns security headers. EN_Card's standalone DENY policy must not
// be shipped as a nested static resource of its same-origin embedded workspace.
await unlink(join(output, '_headers')).catch((error) => {
  if (error.code !== 'ENOENT') throw error;
});
await writeFile(
  join(output, 'source.json'),
  JSON.stringify(
    { format: 'en-card-studio-v1', sourceSha256: source.digest('hex'), files: hashes },
    null,
    2,
  ) + '\n',
);
console.log(JSON.stringify({ target: output, files: Object.keys(hashes).length }));
